/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sam.baomat.cuoiky.sercurity;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Random;

/**
 *
 * @author SamFisher
 */
public class MD5 {

    public static String getMd5(String input) {
        try {

            // Static getInstance method is called with hashing MD5 
            MessageDigest md = MessageDigest.getInstance("MD5");

            // digest() method is called to calculate message digest 
            //  of an input digest() return array of byte 
            byte[] messageDigest = md.digest(input.getBytes());

            // Convert byte array into signum representation 
            BigInteger no = new BigInteger(1, messageDigest);

            // Convert message digest into hex value 
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public static String randomStringWithLength(int length) {
        StringBuilder sb1 = new StringBuilder("");
        for (int i = 0; i < length; i++) {
            Random randomGenerator = new Random();
            int randomInt = randomGenerator.nextInt(9) + 1;
            sb1.append(randomInt);
        }

        return sb1.toString();
    }

    public static String hashData(String input) {
        return getMd5(input);
    }

    // Driver code 
    public static void main(String args[]) {
//        String s = "GeeksForGeeks";
//        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
            System.out.println("randome string: " + randomStringWithLength(3));
    }
}
